namespace: aheath1992
name: insights
version: 1.0.2
readme: README.md
authors:
- Andrew Heath <aheath1992@gmail.com>
description: Ansible modules that will allow the creation and deletion of groups, and assigning users to groups.
license:
- MIT
tags: []
dependencies: {}
repository: "https://github.com/aheath1992/insights"
documentation: "https://github.com/aheath1992/insights/README.md"
homepage: "https://github.com/aheath1992/insights"
issues: "https://github.com/aheath1992/insights/issues"

